{% set name = "qibo" %}
{% set version = "0.2.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibo/archive/v{{ version }}.tar.gz
  sha256: 75c634cfd97551268fad254ca53d6299c31db08ea0f65d752a7a4ecf8c91645b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - poetry
  run:
    - cma
    - numpy
    - joblib
    - python >=3.9,<3.12
    - scipy
    - sympy
    - tabulate
    - hyperopt
    - openqasm3
    - networkx

test:
  imports:
    - qibo

about:
  home: https://github.com/qiboteam/qibo
  summary: A framework for quantum computing with hardware acceleration.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
